
DynSite is an extension of the html publishing scheme of orgmode in Emacs, which simplifies the way that multiple projects with different configurations are defined for one or many websites. 

Features: 

- Set project properties through org files.
- Add folders and subfolders automacitally to projects.
- Inherit project propeties in subprojects with their own configurations.
- Simplify the addition of and switching between multiple sites
  (where each site contains several projects)
- Automatically set relative paths in links of files in subprojects, 
  to ensure access of css and other linked files.

The source code is contained in publish-setup.el

The documentation is found in dynsite.org (orgmode format) and in dynsite.html (html format). The html was produced by using DynSite itself. The setup is found in orgmode.org/config.org and config.el

To try dynsite out:

- Clone the dynsite project from the master branch at: https://github.com/iani/dynsite.git
- Put dynsite.el (or the entire dynsite folder) somewhere in your emacs-lisp load path, 
- and then load the file =config.el=

For example: 

#+BEGIN_SRC emacs-lisp
(load-file "config.el")
#+END_SRC

Ioannis Zannos [2013-10-13 Sun 17:04]

