#+TITLE: Project Properties

Following project properties are collected for reference from chapters /13.1.5 Options for the HTML/LaTeX exporters/ and 
/12.2 Export options/ of org-info.

* config.org options

@<b>These options (properties) are defined in config.org and are inherited in all files of a project and of its subprojects, unless overwitten by [[Individual File Properties]] (see next section).@</b>

Org-info manual section, /13.1.5 Options for the HTML/LaTeX exporters/, refers to the options that are defined via a project's property list. In DynOrg, these properties are defined in the config.org file that is in the top folder of each project. The name of each property is given through the name of an org node, and the value of the property is given by the text that follows it. If the value is a string, it is given as the contents of the node, like this: 

#+BEGIN_EXAMPLE
* style
<link rel="stylesheet" href="./css/org.css" type="text/css"/>
#+END_EXAMPLE

If the value is a short, one-line string or some lisp object (function, number, symbol, etc.) then the name of the property is followed by ":" and the value is given on the same line as the name of the property, like this: 

#+BEGIN_EXAMPLE
* headline-levels: 2
#+END_EXAMPLE

The options that can be used in the config.org file are shown in the following example: 

#+BEGIN_EXAMPLE
* link-up: "http://somesite.net/chapter1"
* link-home:  "http://somesite.net/"
* language: "en"
* customtime: t
* headline-levels: 2
* section-numbers: nil
* section-number-format: '((("1" ".")) . "")
* table-of-contents: t
* preserve-breaks: nil
* archived-trees: nil
* emphasize: t
* sub-superscript: nil
* special-strings: nil
* footnotes: t
* drawers: t
* tags: nil
* todo-keywords: nil
* priority: nil
* TeX-macros: nil
* LaTeX-fragments: nil
* latex-listings: nil
* skip-before-1st-heading: nil
* fixed-width: nil
* timestamps: nil
* author-info: t
* creator-info: t
* tables: t
* table-auto-headline: t
* style-include-default: nil
* style
<link rel="stylesheet" href="./css/org.css" type="text/css"/>
* style-extra: ""
* convert-org-links: t
* inline-images: 'maybe
* html-extension: "html"
* xml-declaration: '(("html" . "<?xml version=\"1.0\" encoding=\"%s\"?>") ("php" . "<?php echo \"<?xml version=\\\"1.0\\\" encoding=\\\"%s\\\" ?>\"; ?>"))
* html-table-tag
<table border="2" cellspacing="0" cellpadding=\"6\" rules=\"groups\" frame=\"hsides\">
* expand-quoted-html'   `org-export-html-expand'
* timestamp'            `org-export-html-with-timestamp'
* publishing-directory' `org-export-publishing-directory'
* preamble'             `org-export-html-preamble'
* postamble'            `org-export-html-postamble'
* auto-preamble'        `org-export-html-auto-preamble'
* auto-postamble'       `org-export-html-auto-postamble'
* author'               `user-full-name'
* email'                `user-mail-address' : `addr;addr;..'
* select-tags'          `org-export-select-tags'
* exclude-tags'         `org-export-exclude-tags'
* latex-image-options'  `org-export-latex-image-default-option'
* file header options
#+END_EXAMPLE

#+BEGIN_EXAMPLE
* title: "the title to be shown (default is the buffer name)"
* author:  "the author (default taken from `user-full-name')"
* date:  "15.5.2011" (note: the doc says: "a date, fixed, of a format string for `format-time-string'"
* email:  "john@doe.info" (default from `user-mail-address')
* description
the page description, e.g. for the XHTML meta tag
* keywords
the page keywords, e.g. for the XHTML meta tag
* language:  "en" (language for HTML, e.g. `en' (`org-export-default-language'))
* text
Some descriptive text to be inserted at the beginning.
Several lines may be given.
* options: "H:2 num:t toc:t \n:nil @:t ::t |:t ^:t f:t TeX:t"
(See below for explanation. I am not sure how the options are to be entered. As one string or how else? 
Besides, many of these options are covered by pub
* bind:        lisp-var lisp-val, e.g.: org-export-latex-low-levels itemize
                    You need to confirm using these, or configure `org-export-allow-BIND'
* link_up:   "../" ;; note: this is the relative path to the folder immediately above the current folder
* link_home: "{{.}}" ;; note: {{.}} creates a relative path to the root folder of the current project
* latex_header
extra line(s) for the LaTeX header, like \usepackage{xyz}
* export_select_tags: "export"
* export_exclude_tags: "exclude"
#+END_EXAMPLE

The examples above are given in org format as they should be written in a config.org. 

Here are the items that can go in the "OPTIONS" line or node above. See examples in org-info for details about how to write these: 

#+BEGIN_EXAMPLE
     H:         set the number of headline levels for export
     num:       turn on/off section-numbers
     toc:       turn on/off table of contents, or set level limit (integer)
     \n:        turn on/off line-break-preservation
     @:         turn on/off quoted HTML tags
     ::         turn on/off fixed-width sections
     |:         turn on/off tables
     ^:         turn on/off TeX-like syntax for sub- and superscripts.  If
                you write "^:{}", `a_{b}' will be interpreted, but
                the simple `a_b' will be left as it is.
     -:         turn on/off conversion of special strings.
     f:         turn on/off footnotes like this[1].
     todo:      turn on/off inclusion of TODO keywords into exported text
     pri:       turn on/off priority cookies
     tags:      turn on/off inclusion of tags, may also be `not-in-toc'
     <:         turn on/off inclusion of any time/date stamps like DEADLINES
     *:         turn on/off emphasized text (bold, italic, underlined)
     TeX:       turn on/off simple TeX macros in plain text
     LaTeX:     turn on/off LaTeX fragments
     skip:      turn on/off skipping the text before the first heading
     author:    turn on/off inclusion of author name/email into exported file
     creator:   turn on/off inclusion of creator info into exported file
     timestamp: turn on/off inclusion creation time into exported file
     d:         turn on/off inclusion of drawers
   These options take effect in both the HTML and LaTeX export, except
for `TeX' and `LaTeX', which are respectively `t' and `nil' for the
LaTeX export.
#+END_EXAMPLE

* Individual File Properties

These options are inserted using org property format at the top of the file that they concern, and they set the properties only for that file. A template of such options can be inserted at the current cursor point of an org file by running the command C-c C-e t (org-insert-export-options-template).

The following is quoted from section 12.2 Export options of the org info manual.

#+BEGIN_EXAMPLE
     #+TITLE:       the title to be shown (default is the buffer name)
     #+AUTHOR:      the author (default taken from `user-full-name')
     #+DATE:        a date, fixed, of a format string for `format-time-string'
     #+EMAIL:       his/her email address (default from `user-mail-address')
     #+DESCRIPTION: the page description, e.g. for the XHTML meta tag
     #+KEYWORDS:    the page keywords, e.g. for the XHTML meta tag
     #+LANGUAGE:    language for HTML, e.g. `en' (`org-export-default-language')
     #+TEXT:        Some descriptive text to be inserted at the beginning.
     #+TEXT:        Several lines may be given.
     #+OPTIONS:     H:2 num:t toc:t \n:nil @:t ::t |:t ^:t f:t TeX:t ...
     #+BIND:        lisp-var lisp-val, e.g.: org-export-latex-low-levels itemize
                    You need to confirm using these, or configure `org-export-allow-BIND'
     #+LINK_UP:     the ``up'' link of an exported page
     #+LINK_HOME:   the ``home'' link of an exported page
     #+LATEX_HEADER: extra line(s) for the LaTeX header, like \usepackage{xyz}
     #+EXPORT_SELECT_TAGS:   Tags that select a tree for export
     #+EXPORT_EXCLUDE_TAGS:  Tags that exclude a tree from export
#+END_EXAMPLE
The OPTIONS line is a compact(1) form to specify export settings.  Here you can:

#+BEGIN_EXAMPLE 
     H:         set the number of headline levels for export
     num:       turn on/off section-numbers
     toc:       turn on/off table of contents, or set level limit (integer)
     \n:        turn on/off line-break-preservation
     @:         turn on/off quoted HTML tags
     ::         turn on/off fixed-width sections
     |:         turn on/off tables
     ^:         turn on/off TeX-like syntax for sub- and superscripts.  If
                you write "^:{}", `a_{b}' will be interpreted, but
                the simple `a_b' will be left as it is.
     -:         turn on/off conversion of special strings.
     f:         turn on/off footnotes like this[1].
     todo:      turn on/off inclusion of TODO keywords into exported text
     pri:       turn on/off priority cookies
     tags:      turn on/off inclusion of tags, may also be `not-in-toc'
     <:         turn on/off inclusion of any time/date stamps like DEADLINES
     *:         turn on/off emphasized text (bold, italic, underlined)
     TeX:       turn on/off simple TeX macros in plain text
     LaTeX:     turn on/off LaTeX fragments
     skip:      turn on/off skipping the text before the first heading
     author:    turn on/off inclusion of author name/email into exported file
     creator:   turn on/off inclusion of creator info into exported file
     timestamp: turn on/off inclusion creation time into exported file
     d:         turn on/off inclusion of drawers
#+END_EXAMPLE

These options take effect in both the HTML and LaTeX export, except
for `TeX' and `LaTeX', which are respectively `t' and `nil' for the
LaTeX export.



